//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCrafter.Utils.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCrafter.Utils.I18n.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        internal static string Auth_EmailExists {
            get {
                return ResourceManager.GetString("Auth_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is not correct..
        /// </summary>
        internal static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string Auth_UsernameExists {
            get {
                return ResourceManager.GetString("Auth_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request contains invalid or incorrect details..
        /// </summary>
        internal static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conflict occurred with the current state of the resource..
        /// </summary>
        internal static string Error_Conflict {
            get {
                return ResourceManager.GetString("Error_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. The sender email address or password may be incorrect..
        /// </summary>
        internal static string Error_Email_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Error_Email_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deliver the email to one or more recipients..
        /// </summary>
        internal static string Error_Email_FailedRecipient {
            get {
                return ResourceManager.GetString("Error_Email_FailedRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more recipient addresses are invalid or unavailable..
        /// </summary>
        internal static string Error_Email_InvalidRecipientAddresses {
            get {
                return ResourceManager.GetString("Error_Email_InvalidRecipientAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have permission to access this resource..
        /// </summary>
        internal static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        internal static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has failed..
        /// </summary>
        internal static string Error_Operation_Failed {
            get {
                return ResourceManager.GetString("Error_Operation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was acknowledged, but no changes were made. The document(s) may already have the expected values..
        /// </summary>
        internal static string Error_OperationAcknowledgedButNoChangesMade {
            get {
                return ResourceManager.GetString("Error_OperationAcknowledgedButNoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be completed..
        /// </summary>
        internal static string Error_OperationFailed {
            get {
                return ResourceManager.GetString("Error_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource is not available..
        /// </summary>
        internal static string Error_ResourceNotAvailable {
            get {
                return ResourceManager.GetString("Error_ResourceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization is required to access this resource..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email account has been successfully added..
        /// </summary>
        internal static string Response_EmailAccount_Added {
            get {
                return ResourceManager.GetString("Response_EmailAccount_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email account has been successfully removed..
        /// </summary>
        internal static string Response_EmailAccount_Removed {
            get {
                return ResourceManager.GetString("Response_EmailAccount_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email password has been successfully updated..
        /// </summary>
        internal static string Response_EmailPassword_Updated {
            get {
                return ResourceManager.GetString("Response_EmailPassword_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email template has been successfully created.
        /// </summary>
        internal static string Response_EmailTemplate_Created {
            get {
                return ResourceManager.GetString("Response_EmailTemplate_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email template has been deleted successfully.
        /// </summary>
        internal static string Response_EmailTemplate_Deleted {
            get {
                return ResourceManager.GetString("Response_EmailTemplate_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email template has been updated successfully.
        /// </summary>
        internal static string Response_EmailTemplate_Updated {
            get {
                return ResourceManager.GetString("Response_EmailTemplate_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful..
        /// </summary>
        internal static string Response_Operation_Succeeded {
            get {
                return ResourceManager.GetString("Response_Operation_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body of email template is required.
        /// </summary>
        internal static string Validation_BodyEmailTemplate_Required {
            get {
                return ResourceManager.GetString("Validation_BodyEmailTemplate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password does not match the original password..
        /// </summary>
        internal static string Validation_ConfirmPassword_Mismatch {
            get {
                return ResourceManager.GetString("Validation_ConfirmPassword_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required and cannot be left empty..
        /// </summary>
        internal static string Validation_ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("Validation_ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address format is invalid..
        /// </summary>
        internal static string Validation_Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_Email_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email password must be exactly 16 characters long..
        /// </summary>
        internal static string Validation_EmailPassword_InvalidLength {
            get {
                return ResourceManager.GetString("Validation_EmailPassword_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email password is required..
        /// </summary>
        internal static string Validation_EmailPassword_Required {
            get {
                return ResourceManager.GetString("Validation_EmailPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template id is required to update resource.
        /// </summary>
        internal static string Validation_EmailTemplateId_Required {
            get {
                return ResourceManager.GetString("Validation_EmailTemplateId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 20 characters..
        /// </summary>
        internal static string Validation_Password_InvalidLength {
            get {
                return ResourceManager.GetString("Validation_Password_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Validation_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholders of email template is required.
        /// </summary>
        internal static string Validation_PlaceholdersEmailTemplate_Required {
            get {
                return ResourceManager.GetString("Validation_PlaceholdersEmailTemplate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject of email template is required.
        /// </summary>
        internal static string Validation_SubjectEmailTemplate_Required {
            get {
                return ResourceManager.GetString("Validation_SubjectEmailTemplate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name is required.
        /// </summary>
        internal static string Validation_TemplateName_Required {
            get {
                return ResourceManager.GetString("Validation_TemplateName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId is required.
        /// </summary>
        internal static string Validation_UserId_Required {
            get {
                return ResourceManager.GetString("Validation_UserId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between 5 and 15 characters..
        /// </summary>
        internal static string Validation_Username_InvalidLength {
            get {
                return ResourceManager.GetString("Validation_Username_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        internal static string Validation_Username_Required {
            get {
                return ResourceManager.GetString("Validation_Username_Required", resourceCulture);
            }
        }
    }
}
